/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults, } from "@stencil/router";
import { BoardSide, ChessPiece, SquareCoordinates, } from "./utils/chess-utils";
import { DirectionalNavigable, } from "./abstraction/DirectionalNavigable";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface ChessBoard {
        "side": BoardSide;
    }
    interface ChessSquare {
        "column": number;
        "piece"?: ChessPiece;
        "row": number;
        "side": BoardSide;
    }
    interface KeyboardNavigable {
    }
    interface KeyboardNavigationListener {
        "navigable": DirectionalNavigable;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLChessBoardElement extends Components.ChessBoard, HTMLStencilElement {
    }
    var HTMLChessBoardElement: {
        prototype: HTMLChessBoardElement;
        new (): HTMLChessBoardElement;
    };
    interface HTMLChessSquareElement extends Components.ChessSquare, HTMLStencilElement {
    }
    var HTMLChessSquareElement: {
        prototype: HTMLChessSquareElement;
        new (): HTMLChessSquareElement;
    };
    interface HTMLKeyboardNavigableElement extends Components.KeyboardNavigable, HTMLStencilElement {
    }
    var HTMLKeyboardNavigableElement: {
        prototype: HTMLKeyboardNavigableElement;
        new (): HTMLKeyboardNavigableElement;
    };
    interface HTMLKeyboardNavigationListenerElement extends Components.KeyboardNavigationListener, HTMLStencilElement {
    }
    var HTMLKeyboardNavigationListenerElement: {
        prototype: HTMLKeyboardNavigationListenerElement;
        new (): HTMLKeyboardNavigationListenerElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "chess-board": HTMLChessBoardElement;
        "chess-square": HTMLChessSquareElement;
        "keyboard-navigable": HTMLKeyboardNavigableElement;
        "keyboard-navigation-listener": HTMLKeyboardNavigationListenerElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface ChessBoard {
        "side"?: BoardSide;
    }
    interface ChessSquare {
        "column": number;
        "onSquareFocused"?: (event: CustomEvent<SquareCoordinates>) => void;
        "piece"?: ChessPiece;
        "row": number;
        "side": BoardSide;
    }
    interface KeyboardNavigable {
        "onDownArrow"?: (event: CustomEvent<any>) => void;
        "onLeftArrow"?: (event: CustomEvent<any>) => void;
        "onRightArrow"?: (event: CustomEvent<any>) => void;
        "onUpArrow"?: (event: CustomEvent<any>) => void;
    }
    interface KeyboardNavigationListener {
        "navigable": DirectionalNavigable;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "chess-board": ChessBoard;
        "chess-square": ChessSquare;
        "keyboard-navigable": KeyboardNavigable;
        "keyboard-navigation-listener": KeyboardNavigationListener;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "chess-board": LocalJSX.ChessBoard & JSXBase.HTMLAttributes<HTMLChessBoardElement>;
            "chess-square": LocalJSX.ChessSquare & JSXBase.HTMLAttributes<HTMLChessSquareElement>;
            "keyboard-navigable": LocalJSX.KeyboardNavigable & JSXBase.HTMLAttributes<HTMLKeyboardNavigableElement>;
            "keyboard-navigation-listener": LocalJSX.KeyboardNavigationListener & JSXBase.HTMLAttributes<HTMLKeyboardNavigationListenerElement>;
        }
    }
}
